CREATE TABLE `board` (
  `board_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시글 번호',
   `title` VARCHAR(255) NOT NULL COMMENT '제목',
  `content` TEXT DEFAULT NULL COMMENT 'board content',
  `regdate` DATETIME NULL DEFAULT NULL COMMENT '등록일',
  PRIMARY KEY (`board_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;